INSERT INTO `subjects` (`id`, `name`, `total_number_hours`, `program_id`) VALUES
(1, 'INDUCCIÓN', 48, 1),
(2, 'Utilizar herramientas informáticas de acuerdo con las necesidades de manejo de información', 48, 1),
(3, 'Establecer requisitos de la solución de software de acuerdo con estándares y procedimiento técnico', 144, 1),
(4, 'Razonar cuantitativamente frente a situaciones susceptibles de ser abordadas de manera matemática en contextos laborales, sociales y personales', 48, 1),
(5, 'Evaluar requisitos de la solución de software de acuerdo con metodologías de análisis y estándares', 288, 1),
(6, 'Enrique Low Murtra-Interactuar en el contexto productivo y social de acuerdo con principios éticos para la construcción de una cultura de paz', 48, 1),
(7, 'APLICACIÓN DE CONOCIMIENTOS DE LAS CIENCIAS NATURALES DE ACUERDO CON SITUACIONES DEL CONTEXTO PRODUCTIVO Y SOCIAL', 48, 1),
(8, 'INTERACTUAR EN LENGUA INGLESA DE FORMA ORAL Y ESCRITA DENTRO DE CONTEXTOS SOCIALES Y LABORALES SEGÚN LOS CRITERIOS ESTABLECIDOS POR EL MARCO COMÚN EUROPEO DE REFERENCIA PARA LAS LENGUAS.', 384, 1),
(9, 'Diseñar la solución de software de acuerdo con procedimientos y requisitos técnicos', 336, 1),
(10, 'Orientar investigación formativa según referentes técnicos', 48, 1),
(11, 'Controlar la calidad del servicio de software de acuerdo con los estándares técnicos', 96, 1),
(12, 'Estructurar propuesta técnica de servicio de tecnología de la información según requisitos técnicos y normativa', 144, 1),
(13, 'DESARROLLAR LA SOLUCIÓN DE SOFTWARE DE ACUERDO CON EL DISEÑO Y METODOLOGÍAS DE DESARROLLO', 240, 1),
(14, 'GENERAR HÁBITOS SALUDABLES DE VIDA MEDIANTE LA APLICACIÓN DE PROGRAMAS DE ACTIVIDAD FÍSICA EN LOS CONTEXTOS PRODUCTIVOS Y SOCIALES - NO ASIGNADO.', 48, 1),
(15, 'DESARROLLAR PROCESOS DE COMUNICACIÓN EFICACES Y EFECTIVOS, TENIENDO EN CUENTA SITUACIONES DE ORDEN SOCIAL, PERSONAL Y PRODUCTIVO. - NO ASIGNADO.', 48, 1),
(16, 'APLICAR PRÁCTICAS DE PROTECCIÓN AMBIENTAL, SEGURIDAD Y SALUD EN EL TRABAJO DE ACUERDO CON LAS POLÍTICAS ORGANIZACIONALES Y LA NORMATIVIDAD VIGENTE.', 48, 1),
(17, 'Implementar la solución de software de acuerdo con los requisitos de operación y modelos de referencia', 48, 1),
(18, 'Gestionar procesos propios de la cultura emprendedora y empresarial de acuerdo con el perfil personal y los requerimientos de los contextos productivo y social (EVALUADO - PILAR ALARCON).', 48, 1),
(19, 'Ejercer derechos fundamentales del trabajo en el marco de la constitución política y los convenios internacionales.', 48, 1),
(20, 'RESULTADOS DE APRENDIZAJE ETAPA PRACTICA', 1, 1);
